definitions:
  constant.ResponseMessage:
    enum:
    - VALIDATION_ERROR
    type: string
    x-enum-varnames:
    - ValidationError
  helper.ErrorResponse:
    properties:
      errorMessage:
        type: string
      message:
        type: string
    type: object
  helper.ErrorValidate:
    properties:
      field:
        items:
          additionalProperties:
            $ref: '#/definitions/helper.Field'
          type: object
        type: array
      message:
        $ref: '#/definitions/constant.ResponseMessage'
    type: object
  helper.Field:
    properties:
      messages:
        items:
          type: string
        type: array
    type: object
  model.CreateSubscriptionDto:
    properties:
      email:
        type: string
    required:
    - email
    type: object
host: localhost:8082
info:
  contact:
    email: soberkoder@gmail.com
    name: API Support
  description: This is a sample service for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /subscription/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Подписка
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateSubscriptionDto'
      produces:
      - application/json
      responses:
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/helper.ErrorValidate'
        "500":
          description: Другие ошибки
          schema:
            $ref: '#/definitions/helper.ErrorResponse'
      summary: Создание подписки
      tags:
      - Подписка
swagger: "2.0"
